\hypertarget{Makefile}{\section{Makefile File Reference}
\label{Makefile}\index{Makefile@{Makefile}}
}
\subsection*{Functions}
\begin{DoxyCompactItemize}
\item 
\hyperlink{Makefile_a54d2d882a8cc61f85bf978b5e4317ab1}{do} (M\-A\-K\-E)-\/C \$\$dir-\/f Makefile \$@
\end{DoxyCompactItemize}
\subsection*{Variables}
\begin{DoxyCompactItemize}
\item 
\hyperlink{Makefile_a290c239123caef8485b75428c4acc522}{S\-U\-B\-D\-I\-R\-S}
\end{DoxyCompactItemize}


\subsection{Function Documentation}
\hypertarget{Makefile_a54d2d882a8cc61f85bf978b5e4317ab1}{\index{Makefile@{Makefile}!do@{do}}
\index{do@{do}!Makefile@{Makefile}}
\subsubsection[{do}]{\setlength{\rightskip}{0pt plus 5cm}do (
\begin{DoxyParamCaption}
\item[{M\-A\-K\-E}]{}
\end{DoxyParamCaption}
)}}\label{Makefile_a54d2d882a8cc61f85bf978b5e4317ab1}


\subsection{Variable Documentation}
\hypertarget{Makefile_a290c239123caef8485b75428c4acc522}{\index{Makefile@{Makefile}!S\-U\-B\-D\-I\-R\-S@{S\-U\-B\-D\-I\-R\-S}}
\index{S\-U\-B\-D\-I\-R\-S@{S\-U\-B\-D\-I\-R\-S}!Makefile@{Makefile}}
\subsubsection[{S\-U\-B\-D\-I\-R\-S}]{\setlength{\rightskip}{0pt plus 5cm}S\-U\-B\-D\-I\-R\-S}}\label{Makefile_a290c239123caef8485b75428c4acc522}
{\bfseries Initial value\-:}
\begin{DoxyCode}
= common logging tcpSocket ClientServer

.PHONY: all clean

all clean:
    \textcolor{keywordflow}{for} dir in $(\hyperlink{ClientServer_2Makefile_a290c239123caef8485b75428c4acc522}{SUBDIRS})
\end{DoxyCode}


Definition at line 1 of file Makefile.

